data:
  source: "data/raw/sample_sales.csv"
  periodicity: "D"

database:
  engine: "duckdb"
  connection: "data/warehouse.duckdb"

model:
  name: "auto_arima"
  save_path: "models/latest_model.pkl"
  mlflow_experiment: "forecasting_experiment"
  seasonal_period: 7
  forecast_horizon: 14
